### ISSUE TITLE
Figure not showing in 06

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshopwhepp-lesson-selection#1]
Figures are not in the repository's fig` folder so they do not show in
https://cms-opendata-workshop.github.io/workshopwhepp-lesson-selection/06-bonus/index.html

**Comment by jmhogan** [comment]
Should be fixed with [9370ce3](https://github.com/cms-opendata-workshop/workshopwhepp-lesson-selection/commit/9370ce3a4e2d87b57c955fd7a2d2da0fdef1fa86)
